version: "{build}"
branches:
  only:
    - master
clone_depth: 10
install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install ruby-debug-ide --no-ri --no-rdoc
  - Install-Product node '0.12.7'
  - npm install -g typescript
  - npm install
build_script:
  - tsc -p ./src
test_script:
  - npm test

environment:
  matrix:
    - ruby_version: "193"
    - ruby_version: "200"
    - ruby_version: "200-x64"
    - ruby_version: "21"
    - ruby_version: "21-x64"
    - ruby_version: "22"
    - ruby_version: "22-x64"